version: '3.1'

services:
  airbnb-server:
    build: .
    command: npm start
      # - /usr/local/bin/adonis
      # - migration:run
    image: douglasso/airbnb-server
    container_name: airbnb-server
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

networks:
  default:
    external:
      name: dev-network